### ISSUE TITLE
Asking for the link of extracted features

### ISSUE THREAD

**Issue by DFrAnC1sL1u** [EdenGabriel/TaskWeave#1]
Thank you for your great work! 
The original extracted feature from the Moment-DETR repository is now missing, and the author of Moment-DETR said he had lost that file as well. 
Have you save this file? Could you share this file with me? Very much thanks!

**Comment by EdenGabriel** [comment]
Thanks for your interesting.
You can find the files about extracted features in this link https://github.com/TencentARC/UMT . Good luck.
If you have any questions, please let me know.

**Comment by DFrAnC1sL1u** [comment]
> Thanks for your interesting. You can find the files about extracted features in this link https://github.com/TencentARC/UMT . Good luck. If you have any questions, please let me know.

Problem solved! Very much thanks!
