### ISSUE TITLE
Cannot reproduce the product (Both training and inference) 

### ISSUE THREAD

**Issue by EGreyGhost** [EdenGabriel/TaskWeave#2]
I trained your model based on all your configurations on a single NVIDIA A40, and got the result that is about 1% lower than yours (As shown in eval.log.txt and my_inference.txt).
Moreover, I used the checkpoint you provided in ./results/best_model_mr/model_best.ckpt and found that the evaluation result on val dataset is also about 1% lower than reported (As shown in ckpt_inference.txt). Besides, that result do not match the evaluation result of any epoch in ./results/best_model_mr/eval.log.txt.  That makes me confuse a lot...
My environment is Python 3.7.16 with Pytorch 1.11.0+cu113 and Torchvision 0.12.0+cu113. Basic settings are shown in my_inference.txt and ckpt_inference.txt. Could you please help me figure out the reason? Thanks.
[eval.log.txt](https://github.com/EdenGabriel/TaskWeave/files/15331813/eval.log.txt)
[my_inference.txt](https://github.com/EdenGabriel/TaskWeave/files/15331817/my_inference.txt)
[ckpt_inference.txt](https://github.com/EdenGabriel/TaskWeave/files/15331819/ckpt_inference.txt)

**Comment by EdenGabriel** [comment]
HI，EGreyGhost
Thanks for your interesting.
For the best_mr setting, you should adopt the _mr2hd_ strategy, which involves uncommenting lines [L127 ](https://github.com/EdenGabriel/TaskWeave/blob/9aede8692760c02a348cad4fd190403c9df9b6c4/taskweave/model.py#L127) to [L163 ](https://github.com/EdenGabriel/TaskWeave/blob/9aede8692760c02a348cad4fd190403c9df9b6c4/taskweave/model.py#L163) in the code and commenting out lines [L163](https://github.com/EdenGabriel/TaskWeave/blob/9aede8692760c02a348cad4fd190403c9df9b6c4/taskweave/model.py#L163) to [L203](https://github.com/EdenGabriel/TaskWeave/blob/9aede8692760c02a348cad4fd190403c9df9b6c4/taskweave/model.py#L203). Once these changes are made, you can proceed with testing the checkpoint.
Additionally, there are some potential variations on performance due to software and hardware environments. 
Feel free to share your results.

**Comment by EdenGabriel** [comment]
Long time inactivity, closed. 
If you have any questions, please feel free to discuss

**Comment by MasterBeeee** [comment]
> HI，EGreyGhost Thanks for your interesting. For the best_mr setting, you should adopt the _mr2hd_ strategy, which involves uncommenting lines [L127 ](https://github.com/EdenGabriel/TaskWeave/blob/9aede8692760c02a348cad4fd190403c9df9b6c4/taskweave/model.py#L127) to [L163 ](https://github.com/EdenGabriel/TaskWeave/blob/9aede8692760c02a348cad4fd190403c9df9b6c4/taskweave/model.py#L163) in the code and commenting out lines [L163](https://github.com/EdenGabriel/TaskWeave/blob/9aede8692760c02a348cad4fd190403c9df9b6c4/taskweave/model.py#L163) to [L203](https://github.com/EdenGabriel/TaskWeave/blob/9aede8692760c02a348cad4fd190403c9df9b6c4/taskweave/model.py#L203). Once these changes are made, you can proceed with testing the checkpoint. Additionally, there are some potential variations on performance due to software and hardware environments. Feel free to share your results.

Hi, Thanks for your work, i have a  following question
What changes should make on the code  if I want to use the ``Bi-MRHD`` strategy(maybe just uncomment all lines from [L127 ](https://github.com/EdenGabriel/TaskWeave/blob/9aede8692760c02a348cad4fd190403c9df9b6c4/taskweave/model.py#L127) -[L203](https://github.com/EdenGabriel/TaskWeave/blob/9aede8692760c02a348cad4fd190403c9df9b6c4/taskweave/model.py#L203)?), ``MR-HD`` strategy and ``HD-MR`` strategy? 
Or is that uncomment all lines and following the original code order (mr2hd then hd2mr) to implement the ``MR-HD`` and then change the code order (hd2mr then mr2hd) to implement the ``HD-MR``? Then what should ``Bi-MRHD`` change?

**Comment by EdenGabriel** [comment]
You just need to follow the order of mr2hd first and then hd2mr to achieve Bi-MRHD.
like this:
```python
        epoch_thres = 100
        if epoch_i == None or epoch_i + 1 > epoch_thres: # epoch_i == None for inference
            #mr2hd
            hs, reference, mr_memory, hd_memory_first = self.transformer(src, ~tmp_mask, self.query_embed.weight, pos, video_length=video_length)
            # hs: torch.Size([2, 32, 10, 256]) # layers, bsz, queries, dim
            outputs_class = self.class_embed(hs)  # (#layers, batch_size, #queries, #classes)
            reference_before_sigmoid = inverse_sigmoid(reference)
            tmp = self.span_embed(hs)
            outputs_coord = tmp + reference_before_sigmoid
            if self.span_loss_type == "l1":
                outputs_coord = outputs_coord.sigmoid()
            # out = {'pred_logits': outputs_class[-1], 'pred_spans': outputs_coord[-1]}

            duration = 150
            mr2hd_mask = span_cxw_to_xx(outputs_coord.clone()[-1])*duration
            mr2hd_mask = torch.clamp(mr2hd_mask, min=0,max=duration-1).int()
            one_hot_labels = torch.zeros(mr2hd_mask.shape[0], mr2hd_mask.shape[1],duration).to(mr2hd_mask.device)
            st_indics,ed_indics = mr2hd_mask.transpose(1,2)[:,0],mr2hd_mask.transpose(1,2)[:,1]
            mr2hd_tmp_mask = (st_indics[:, :, None] <= torch.arange(duration)[None, None, :].to(mr2hd_mask.device)) & (ed_indics[:, :, None] >= torch.arange(duration)[None, None, :].to(mr2hd_mask.device))
            one_hot_labels[mr2hd_tmp_mask] = 1
            one_hot_labels = torch.sum(one_hot_labels,dim=1,keepdim=True).view(mr2hd_mask.shape[0], duration//2, 2) #32,1,150
            mask_tensor = (one_hot_labels[:, :, 0] + one_hot_labels[:, :, 1]) / 2
            norms = torch.norm(mask_tensor, p=2, dim=1) 
            mask_norm = mask_tensor / norms[:, None] 
            mask_norm = mask_norm.unsqueeze(2) 

            # hd2mr
            pos_global_local = self.saliency_proj_local(self.saliency_proj_linear(hd_memory_first).transpose(1, 2)).transpose(1, 2)
            saliency_scores = self.output_saliency(pos_global_local).squeeze(-1) + torch.sum(hd_memory_first,dim=-1).squeeze(-1)/ np.sqrt(self.hidden_dim)
            # one_hot_labels = torch.zeros(mr2hd_mask.shape[0], mr2hd_mask.shape[1],duration).to(mr2hd_mask.device)
            saliency_scores = saliency_scores.unsqueeze(1)

            batch_means = torch.mean(saliency_scores, dim=2, keepdim=True) 
            saliency_mask = torch.where(saliency_scores > batch_means, torch.ones_like(saliency_scores), torch.zeros_like(saliency_scores))
            saliency_mask = saliency_mask.permute(0,2,1) # 32,75,1
            saliency_mask = saliency_mask.expand(saliency_mask.shape[0],video_length,src_vid.shape[-1])
            
            src[:,:video_length] = src[:,:video_length] + src[:,:video_length]*saliency_mask
            # src[:,:video_length] = src[:,:video_length]*saliency_mask
            hs, reference, mr_memory, hd_memory = self.transformer(src, ~tmp_mask, self.query_embed.weight, pos, video_length=video_length)
            # hs: torch.Size([2, 32, 10, 256]) # layers, bsz, queries, dim
            outputs_class = self.class_embed(hs)  # (#layers, batch_size, #queries, #classes)
            reference_before_sigmoid = inverse_sigmoid(reference)
            tmp = self.span_embed(hs)
            outputs_coord = tmp + reference_before_sigmoid
            if self.span_loss_type == "l1":
                outputs_coord = outputs_coord.sigmoid()
            out = {'pred_logits': outputs_class[-1], 'pred_spans': outputs_coord[-1]}

            pos_global_local = self.saliency_proj_local(self.saliency_proj_linear(hd_memory_first+hd_memory_first*mask_norm).transpose(1, 2)).transpose(1, 2)
            out["saliency_scores"] = self.output_saliency(pos_global_local).squeeze(-1) + torch.sum(hd_memory_first,dim=-1).squeeze(-1)/ np.sqrt(self.hidden_dim)
```

**Comment by MasterBeeee** [comment]
Thanks for your quick reply.
How to use MR_HD strategy?

**Comment by EdenGabriel** [comment]
Like this:
```python        
        # MR-HD: mr2hd --> hd2mr
        epoch_thres = threshold_epoch
        if epoch_i == None or epoch_i + 1 > epoch_thres: # epoch_i == None for inference
            if epoch_i + 1 < epoch_thres + threshold_epoch//2:
                #mr2hd
                ...
            else:
                #hd2mr
                ...
        else:
            hs, reference, mr_memory, hd_memory = self.transformer(src, ~tmp_mask, self.query_embed.weight, pos, video_length=video_length)
            ...
```
