### ISSUE TITLE
Encountering TypeError while running inference.

### ISSUE THREAD

**Issue by uday-me** [EdenGabriel/TaskWeave#3]
I am trying to run the run.py script, however I get the following error each time : TypeError: forward() missing 1 required positional argument: 'epoch_i'.

However on passing the epoch_i as None (as mentioned in "model.py") in the model_inputs(line 49). I get the error "RuntimeError: Given normalized_shape=[2818], expected input with shape [*, 2818], but got input of size[1, 75, 514]".

Please suggest a solution for this.

**Comment by EdenGabriel** [comment]
In the train script, shape of features should be 2304(slowfast)+512(clip).
It looks like you only have clip features. You should provide the slowfast feature for your test video,

I believe you have the same issue as this one. [QD-DETR issue](https://github.com/wjun0830/QD-DETR/issues/3) Please refer to it.

**Comment by uday-me** [comment]
Thank you for your kind response. Will you also be releasing a checkpoint only based on CLIP features ?

**Comment by EdenGabriel** [comment]
Currently, we do not have a checkpoint based on CLIP-only features. 
However, you can train it yourself; it takes less than 2 hours to train a CLIP-only model.

**Comment by uday-me** [comment]
Sure, Thank you for your reply.
