### ISSUE TITLE
Cannot reproduce the results

### ISSUE THREAD

**Issue by awkrail** [EdenGabriel/TaskWeave#4]
@EdenGabriel 
Hi, I met the same issue #2. 
As you suggested, I tried to remove comment out from L127 to L163 and comment out L164 to L202 and run the code, but cannot reproduce the results. The reproduced scores are lower 1~2% from the paper. In addition, I cannot reproduce the results with the checkpoint you provided.

Could you please help me figure out the reason?

**Comment by awkrail** [comment]
According the [saved score](https://github.com/EdenGabriel/TaskWeave/tree/master/results/best_model_mr) in this repository, the scores are here. MR results (R@1 and mAP) are same to the paper, but HD scores are different from the paper (lower than the paper).
```
    "brief": {
        "MR-full-R1@0.5": 64.26,
        "MR-full-R1@0.7": 50.06,
        "MR-full-mAP": 45.38,
        "MR-full-mAP@0.5": 65.39,
        "MR-full-mAP@0.75": 46.47,
        "MR-long-mAP": 53.96,
        "MR-middle-mAP": 47.19,
        "MR-short-mAP": 7.62,
        "HL-min-Fair-mAP": 75.13,
        "HL-min-Fair-Hit1": 76.39,
        "HL-min-Good-mAP": 63.81,
        "HL-min-Good-Hit1": 74.39,
        "HL-min-VeryGood-mAP": 38.73,
        "HL-min-VeryGood-Hit1": 62.84
    },
```

**Comment by EdenGabriel** [comment]
It is normal. In order to get better HD results, you need to adopt another strategy (hd2mr).
Feel free to share your results.
If you have any questions, please feel free to discuss.

**Comment by EdenGabriel** [comment]
results/best_model_hd: hd2mr strategy
results/best_model_mr: mr2hd strategy
In addition, you can check the configuration in the opt.json file in files. Maybe it will help you. 
If you have any questions, please feel free to discuss.

**Comment by awkrail** [comment]
@EdenGabriel Thank you for your quick reply. 
So, to reproduce the reported scores in the paper, I need to train two models based on strategy (HD2MR and MR2HD), and evaluate each of them for MR and HD, respectively. Is this correct?

Or, I train a single model, but have to choose the appropriate strategy (HD2MR or MR2HD) when evaluating the models?

**Comment by EdenGabriel** [comment]
exactly.

**Comment by EdenGabriel** [comment]
exactly.

**Comment by awkrail** [comment]
Sorry, would I ask you which one is correct? The former or the latter?

**Comment by EdenGabriel** [comment]
Strictly speaking, former is more correct.
However, since the mr2hd and hd2mr strategies do not involve the network parameters to be trained. So, theoretically, after training a model based on a certain strategy, another strategy can also be used for inference. I have not tried this.

**Comment by awkrail** [comment]
I got it. I will try. Thank you.
