### ISSUE TITLE
Cant find the implement of "Task-dependent Joint Loss"

### ISSUE THREAD

**Issue by tjhd1475** [EdenGabriel/TaskWeave#5]
Thank for your great work! when i read this paper, i dont really understand the statement of "Task-dependent Joint Loss", so i come to read the code, but i cant find the implement in SetCriterion, would you please point out for me?

**Comment by EdenGabriel** [comment]
Thanks for your interests.
You can find more details about joint loss from [train.py#L71](https://github.com/EdenGabriel/TaskWeave/blob/3b57e035597bca8d040e4602d7af253fe947dd14/taskweave/train.py#L71) to [train.py#L84](https://github.com/EdenGabriel/TaskWeave/blob/3b57e035597bca8d040e4602d7af253fe947dd14/taskweave/train.py#L84).
If you have any questions, please feel free to discuss.

**Comment by tjhd1475** [comment]
> Thanks for your interests. You can find more details about joint loss from [train.py#L71](https://github.com/EdenGabriel/TaskWeave/blob/3b57e035597bca8d040e4602d7af253fe947dd14/taskweave/train.py#L71) to [train.py#L84](https://github.com/EdenGabriel/TaskWeave/blob/3b57e035597bca8d040e4602d7af253fe947dd14/taskweave/train.py#L84). If you have any questions, please feel free to discuss.

thanks for your reply
